"""made previous_ads field not null

Revision ID: 3584d71814ce
Revises: d71c33aaf38b
Create Date: 2024-12-08 16:25:32.634186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3584d71814ce'
down_revision: Union[str, None] = 'd71c33aaf38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'previous_ads',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'previous_ads',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
