"""added previous_ads field to user model as jsonified string

Revision ID: d71c33aaf38b
Revises: b737a6d5ba69
Create Date: 2024-12-08 16:06:43.453939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision: str = 'd71c33aaf38b'
down_revision: Union[str, None] = 'b737a6d5ba69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('previous_ads', String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'previous_ads')
    # ### end Alembic commands ###
